export type StockStatus = "In Stock" | "Low Stock" | "Out of Stock";

export interface StockItem {
  id: string;
  sku: string;
  barcode: string;
  productName: string;
  category: string;
  warehouse: string;
  location: string;
  availableQty: number;
  unit: string;
  status: StockStatus;
  stockValue: number;
}

export const STOCK_ITEMS: StockItem[] = [
  {
    id: "1",
    sku: "SOF-001",
    barcode: "8901234567890",
    productName: "3 Seater Sofa",
    category: "Sofas",
    warehouse: "Main Warehouse",
    location: "Aisle 01 - Rack 01",
    availableQty: 15,
    unit: "Nos",
    status: "In Stock",
    stockValue: 487500,
  },
  {
    id: "2",
    sku: "BED-001",
    barcode: "8901234567891",
    productName: "King Size Bed",
    category: "Beds",
    warehouse: "Main Warehouse",
    location: "Aisle 02 - Rack 03",
    availableQty: 10,
    unit: "Nos",
    status: "In Stock",
    stockValue: 390000,
  },
  {
    id: "3",
    sku: "DIN-TBL-001",
    barcode: "8901234567892",
    productName: "Dining Table 6 Seater",
    category: "Dining",
    warehouse: "Main Warehouse",
    location: "Aisle 03 - Rack 02",
    availableQty: 5,
    unit: "Nos",
    status: "Low Stock",
    stockValue: 185000,
  },
  {
    id: "4",
    sku: "DIN-CHR-001",
    barcode: "8901234567893",
    productName: "Dining Chair",
    category: "Dining",
    warehouse: "HSR Layout",
    location: "Aisle 01 - Rack 04",
    availableQty: 18,
    unit: "Nos",
    status: "In Stock",
    stockValue: 72000,
  },
  {
    id: "5",
    sku: "WRD-003",
    barcode: "8901234567894",
    productName: "Wardrobe 3 Door",
    category: "Wardrobes",
    warehouse: "Marathahalli",
    location: "Aisle 02 - Rack 01",
    availableQty: 2,
    unit: "Nos",
    status: "Low Stock",
    stockValue: 26000,
  },
  {
    id: "6",
    sku: "TBL-CT-001",
    barcode: "8901234567895",
    productName: "Center Table",
    category: "Tables",
    warehouse: "Jayanagar",
    location: "Aisle 01 - Rack 03",
    availableQty: 7,
    unit: "Nos",
    status: "In Stock",
    stockValue: 45500,
  },
  {
    id: "7",
    sku: "TVU-001",
    barcode: "8901234567896",
    productName: "TV Unit",
    category: "Tables",
    warehouse: "Whitefield",
    location: "Aisle 03 - Rack 05",
    availableQty: 12,
    unit: "Nos",
    status: "In Stock",
    stockValue: 120000,
  },
  {
    id: "8",
    sku: "CHR-OF-001",
    barcode: "8901234567897",
    productName: "Office Chair",
    category: "Chairs",
    warehouse: "Main Warehouse",
    location: "Aisle 02 - Rack 02",
    availableQty: 20,
    unit: "Nos",
    status: "In Stock",
    stockValue: 60000,
  },
  {
    id: "9",
    sku: "MAT-001",
    barcode: "8901234567898",
    productName: "Mattress Queen Size",
    category: "Mattresses",
    warehouse: "Main Warehouse",
    location: "Aisle 04 - Rack 01",
    availableQty: 0,
    unit: "Nos",
    status: "Out of Stock",
    stockValue: 0,
  },
  {
    id: "10",
    sku: "DEC-001",
    barcode: "8901234567899",
    productName: "Decorative Wall Mirror",
    category: "Decor",
    warehouse: "Jayanagar",
    location: "Aisle 05 - Rack 01",
    availableQty: 8,
    unit: "Nos",
    status: "In Stock",
    stockValue: 16000,
  },
  {
    id: "11",
    sku: "ACC-001",
    barcode: "8901234567900",
    productName: "Accent Table",
    category: "Tables",
    warehouse: "HSR Layout",
    location: "Aisle 05 - Rack 02",
    availableQty: 9,
    unit: "Nos",
    status: "In Stock",
    stockValue: 18000,
  },
  {
    id: "12",
    sku: "RUG-001",
    barcode: "8901234567901",
    productName: "Area Rug",
    category: "Decor",
    warehouse: "Marathahalli",
    location: "Aisle 03 - Rack 01",
    availableQty: 4,
    unit: "Nos",
    status: "Low Stock",
    stockValue: 12000,
  },
  {
    id: "13",
    sku: "BDN-001",
    barcode: "8901234567902",
    productName: "Bedroom Nightstand",
    category: "Beds",
    warehouse: "Jayanagar",
    location: "Aisle 04 - Rack 02",
    availableQty: 6,
    unit: "Nos",
    status: "In Stock",
    stockValue: 30000,
  },
  {
    id: "14",
    sku: "CAB-001",
    barcode: "8901234567903",
    productName: "TV Cabinet",
    category: "Tables",
    warehouse: "Whitefield",
    location: "Aisle 03 - Rack 05",
    availableQty: 0,
    unit: "Nos",
    status: "Out of Stock",
    stockValue: 0,
  },
  {
    id: "15",
    sku: "SHE-001",
    barcode: "8901234567904",
    productName: "Display Shelf",
    category: "Wardrobes",
    warehouse: "Main Warehouse",
    location: "Aisle 02 - Rack 04",
    availableQty: 14,
    unit: "Nos",
    status: "In Stock",
    stockValue: 56000,
  },
];

export const CATEGORIES = [
  "All Categories",
  "Sofas",
  "Beds",
  "Dining",
  "Wardrobes",
  "Tables",
  "Chairs",
  "Mattresses",
  "Decor",
];

export const WAREHOUSES = [
  "All Warehouses",
  "Main Warehouse",
  "HSR Layout",
  "Marathahalli",
  "Jayanagar",
  "Whitefield",
];

export const LOCATIONS = [
  "All Locations",
  "Aisle 01 - Rack 01",
  "Aisle 01 - Rack 03",
  "Aisle 01 - Rack 04",
  "Aisle 02 - Rack 01",
  "Aisle 02 - Rack 02",
  "Aisle 02 - Rack 03",
  "Aisle 03 - Rack 02",
  "Aisle 03 - Rack 05",
  "Aisle 04 - Rack 01",
  "Aisle 05 - Rack 01",
];

export const STATUSES: (StockStatus | "All Status")[] = [
  "All Status",
  "In Stock",
  "Low Stock",
  "Out of Stock",
];
