export type ProductionStatus = "In Progress" | "Completed" | "Pending" | "On Hold" | "Cancelled";

export interface ProductionStep {
  step: number;
  workCenter: string;
  plannedQty: number;
  completedQty: number;
  status: ProductionStatus;
}

export interface ProductionOrder {
  id: string;
  orderNo: string;
  product: string;
  unit: string;
  outlet: string;
  plannedQty: number;
  completedQty: number;
  status: ProductionStatus;
  plannedDate: string;
  startDate: string;
  expectedCompletion: string;
  actualCompletion: string | null;
  createdBy: string;
  createdDate: string;
  lastUpdated: string;
  notes: string;
  steps: ProductionStep[];
}

export const PRODUCTION_ORDERS: ProductionOrder[] = [
  {
    id: "1",
    orderNo: "PO-1256",
    product: "3 Seater Sofa",
    unit: "Unit 1",
    outlet: "HSR Layout",
    plannedQty: 100,
    completedQty: 60,
    status: "In Progress",
    plannedDate: "15 May 2025",
    startDate: "05 May 2025",
    expectedCompletion: "19 May 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "01 May 2025 10:30 AM",
    lastUpdated: "17 May 2025 03:45 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 100, completedQty: 100, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 100, completedQty: 80, status: "In Progress" },
      { step: 3, workCenter: "Foam Section", plannedQty: 100, completedQty: 40, status: "In Progress" },
      { step: 4, workCenter: "Stitching Section", plannedQty: 100, completedQty: 40, status: "Pending" },
      { step: 5, workCenter: "Finishing Section", plannedQty: 100, completedQty: 0, status: "Pending" },
      { step: 6, workCenter: "Packing Section", plannedQty: 100, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "2",
    orderNo: "PO-1255",
    product: "King Size Bed",
    unit: "Unit 2",
    outlet: "Koramangala",
    plannedQty: 80,
    completedQty: 80,
    status: "Completed",
    plannedDate: "10 May 2025",
    startDate: "28 Apr 2025",
    expectedCompletion: "10 May 2025",
    actualCompletion: "09 May 2025",
    createdBy: "Ravi Kumar",
    createdDate: "26 Apr 2025 09:15 AM",
    lastUpdated: "09 May 2025 06:20 PM",
    notes: "Completed ahead of schedule.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 80, completedQty: 80, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 80, completedQty: 80, status: "Completed" },
      { step: 3, workCenter: "Foam Section", plannedQty: 80, completedQty: 80, status: "Completed" },
      { step: 4, workCenter: "Finishing Section", plannedQty: 80, completedQty: 80, status: "Completed" },
      { step: 5, workCenter: "Packing Section", plannedQty: 80, completedQty: 80, status: "Completed" },
    ],
  },
  {
    id: "3",
    orderNo: "PO-1254",
    product: "Dining Chair",
    unit: "Unit 1",
    outlet: "Marathahalli",
    plannedQty: 200,
    completedQty: 240,
    status: "In Progress",
    plannedDate: "12 May 2025",
    startDate: "02 May 2025",
    expectedCompletion: "18 May 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "01 May 2025 11:00 AM",
    lastUpdated: "16 May 2025 02:10 PM",
    notes: "Extra batch added mid-run.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 200, completedQty: 200, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 200, completedQty: 200, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 200, completedQty: 180, status: "In Progress" },
      { step: 4, workCenter: "Packing Section", plannedQty: 200, completedQty: 120, status: "In Progress" },
    ],
  },
  {
    id: "4",
    orderNo: "PO-1253",
    product: "Wardrobe 3 Door",
    unit: "Unit 3",
    outlet: "Jayanagar",
    plannedQty: 50,
    completedQty: 10,
    status: "In Progress",
    plannedDate: "18 May 2025",
    startDate: "10 May 2025",
    expectedCompletion: "25 May 2025",
    actualCompletion: null,
    createdBy: "Sneha Reddy",
    createdDate: "08 May 2025 04:30 PM",
    lastUpdated: "17 May 2025 11:00 AM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 50, completedQty: 30, status: "In Progress" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 50, completedQty: 10, status: "In Progress" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 50, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 50, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "5",
    orderNo: "PO-1252",
    product: "Center Table",
    unit: "Unit 1",
    outlet: "Whitefield",
    plannedQty: 60,
    completedQty: 60,
    status: "Completed",
    plannedDate: "05 May 2025",
    startDate: "28 Apr 2025",
    expectedCompletion: "05 May 2025",
    actualCompletion: "04 May 2025",
    createdBy: "Admin",
    createdDate: "26 Apr 2025 09:00 AM",
    lastUpdated: "04 May 2025 05:40 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 60, completedQty: 60, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 60, completedQty: 60, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 60, completedQty: 60, status: "Completed" },
      { step: 4, workCenter: "Packing Section", plannedQty: 60, completedQty: 60, status: "Completed" },
    ],
  },
  {
    id: "6",
    orderNo: "PO-1251",
    product: "TV Unit",
    unit: "Unit 2",
    outlet: "HSR Layout",
    plannedQty: 40,
    completedQty: 0,
    status: "Pending",
    plannedDate: "20 May 2025",
    startDate: "—",
    expectedCompletion: "28 May 2025",
    actualCompletion: null,
    createdBy: "Karthik Iyer",
    createdDate: "15 May 2025 01:00 PM",
    lastUpdated: "15 May 2025 01:00 PM",
    notes: "Awaiting raw material delivery.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 40, completedQty: 0, status: "Pending" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 40, completedQty: 0, status: "Pending" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 40, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 40, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "7",
    orderNo: "PO-1250",
    product: "Office Chair",
    unit: "Unit 1",
    outlet: "Koramangala",
    plannedQty: 150,
    completedQty: 114,
    status: "In Progress",
    plannedDate: "22 May 2025",
    startDate: "12 May 2025",
    expectedCompletion: "29 May 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "10 May 2025 10:00 AM",
    lastUpdated: "17 May 2025 09:30 AM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 150, completedQty: 150, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 150, completedQty: 140, status: "In Progress" },
      { step: 3, workCenter: "Upholstery Section", plannedQty: 150, completedQty: 114, status: "In Progress" },
      { step: 4, workCenter: "Packing Section", plannedQty: 150, completedQty: 60, status: "In Progress" },
    ],
  },
  {
    id: "8",
    orderNo: "PO-1249",
    product: "Dining Table 6 Seater",
    unit: "Unit 2",
    outlet: "Marathahalli",
    plannedQty: 30,
    completedQty: 0,
    status: "Pending",
    plannedDate: "25 May 2025",
    startDate: "—",
    expectedCompletion: "02 Jun 2025",
    actualCompletion: null,
    createdBy: "Divya Shetty",
    createdDate: "16 May 2025 03:20 PM",
    lastUpdated: "16 May 2025 03:20 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 30, completedQty: 0, status: "Pending" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 30, completedQty: 0, status: "Pending" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 30, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 30, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "9",
    orderNo: "PO-1248",
    product: "Side Table",
    unit: "Unit 1",
    outlet: "Jayanagar",
    plannedQty: 100,
    completedQty: 100,
    status: "Completed",
    plannedDate: "02 May 2025",
    startDate: "24 Apr 2025",
    expectedCompletion: "02 May 2025",
    actualCompletion: "01 May 2025",
    createdBy: "Admin",
    createdDate: "22 Apr 2025 08:45 AM",
    lastUpdated: "01 May 2025 04:15 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 100, completedQty: 100, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 100, completedQty: 100, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 100, completedQty: 100, status: "Completed" },
      { step: 4, workCenter: "Packing Section", plannedQty: 100, completedQty: 100, status: "Completed" },
    ],
  },
  {
    id: "10",
    orderNo: "PO-1247",
    product: "Bookshelf",
    unit: "Unit 3",
    outlet: "Whitefield",
    plannedQty: 25,
    completedQty: 0,
    status: "On Hold",
    plannedDate: "28 May 2025",
    startDate: "14 May 2025",
    expectedCompletion: "05 Jun 2025",
    actualCompletion: null,
    createdBy: "Manoj Pillai",
    createdDate: "12 May 2025 02:00 PM",
    lastUpdated: "16 May 2025 10:05 AM",
    notes: "On hold — plywood shortage at Unit 3.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 25, completedQty: 8, status: "On Hold" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 25, completedQty: 0, status: "Pending" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 25, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 25, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "11",
    orderNo: "PO-1246",
    product: "3 Seater Sofa",
    unit: "Unit 2",
    outlet: "HSR Layout",
    plannedQty: 90,
    completedQty: 90,
    status: "Completed",
    plannedDate: "27 Apr 2025",
    startDate: "18 Apr 2025",
    expectedCompletion: "27 Apr 2025",
    actualCompletion: "26 Apr 2025",
    createdBy: "Admin",
    createdDate: "16 Apr 2025 09:10 AM",
    lastUpdated: "26 Apr 2025 05:30 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 90, completedQty: 90, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 90, completedQty: 90, status: "Completed" },
      { step: 3, workCenter: "Foam Section", plannedQty: 90, completedQty: 90, status: "Completed" },
      { step: 4, workCenter: "Stitching Section", plannedQty: 90, completedQty: 90, status: "Completed" },
      { step: 5, workCenter: "Finishing Section", plannedQty: 90, completedQty: 90, status: "Completed" },
      { step: 6, workCenter: "Packing Section", plannedQty: 90, completedQty: 90, status: "Completed" },
    ],
  },
  {
    id: "12",
    orderNo: "PO-1245",
    product: "Office Chair",
    unit: "Unit 3",
    outlet: "Koramangala",
    plannedQty: 120,
    completedQty: 45,
    status: "In Progress",
    plannedDate: "24 May 2025",
    startDate: "14 May 2025",
    expectedCompletion: "31 May 2025",
    actualCompletion: null,
    createdBy: "Karthik Iyer",
    createdDate: "12 May 2025 11:20 AM",
    lastUpdated: "17 May 2025 04:00 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 120, completedQty: 120, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 120, completedQty: 70, status: "In Progress" },
      { step: 3, workCenter: "Upholstery Section", plannedQty: 120, completedQty: 45, status: "In Progress" },
      { step: 4, workCenter: "Packing Section", plannedQty: 120, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "13",
    orderNo: "PO-1244",
    product: "King Size Bed",
    unit: "Unit 1",
    outlet: "Marathahalli",
    plannedQty: 60,
    completedQty: 35,
    status: "In Progress",
    plannedDate: "20 Apr 2025",
    startDate: "10 Apr 2025",
    expectedCompletion: "27 Apr 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "08 Apr 2025 10:00 AM",
    lastUpdated: "17 May 2025 03:45 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 60, completedQty: 60, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 60, completedQty: 55, status: "In Progress" },
      { step: 3, workCenter: "Foam Section", plannedQty: 60, completedQty: 35, status: "In Progress" },
      { step: 4, workCenter: "Finishing Section", plannedQty: 60, completedQty: 0, status: "Pending" },
      { step: 5, workCenter: "Packing Section", plannedQty: 60, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "14",
    orderNo: "PO-1243",
    product: "Wardrobe 3 Door",
    unit: "Unit 2",
    outlet: "Jayanagar",
    plannedQty: 35,
    completedQty: 12,
    status: "In Progress",
    plannedDate: "26 May 2025",
    startDate: "16 May 2025",
    expectedCompletion: "02 Jun 2025",
    actualCompletion: null,
    createdBy: "Sneha Reddy",
    createdDate: "14 May 2025 01:40 PM",
    lastUpdated: "17 May 2025 12:15 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 35, completedQty: 25, status: "In Progress" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 35, completedQty: 12, status: "In Progress" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 35, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 35, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "15",
    orderNo: "PO-1242",
    product: "Center Table",
    unit: "Unit 3",
    outlet: "Whitefield",
    plannedQty: 70,
    completedQty: 70,
    status: "Completed",
    plannedDate: "15 Apr 2025",
    startDate: "06 Apr 2025",
    expectedCompletion: "15 Apr 2025",
    actualCompletion: "14 Apr 2025",
    createdBy: "Admin",
    createdDate: "04 Apr 2025 09:30 AM",
    lastUpdated: "14 Apr 2025 06:00 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 70, completedQty: 70, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 70, completedQty: 70, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 70, completedQty: 70, status: "Completed" },
      { step: 4, workCenter: "Packing Section", plannedQty: 70, completedQty: 70, status: "Completed" },
    ],
  },
  {
    id: "16",
    orderNo: "PO-1241",
    product: "TV Unit",
    unit: "Unit 1",
    outlet: "HSR Layout",
    plannedQty: 45,
    completedQty: 20,
    status: "In Progress",
    plannedDate: "23 May 2025",
    startDate: "13 May 2025",
    expectedCompletion: "30 May 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "11 May 2025 02:25 PM",
    lastUpdated: "17 May 2025 10:50 AM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 45, completedQty: 40, status: "In Progress" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 45, completedQty: 20, status: "In Progress" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 45, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 45, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "17",
    orderNo: "PO-1240",
    product: "Dining Chair",
    unit: "Unit 2",
    outlet: "Koramangala",
    plannedQty: 250,
    completedQty: 250,
    status: "Completed",
    plannedDate: "12 Apr 2025",
    startDate: "01 Apr 2025",
    expectedCompletion: "12 Apr 2025",
    actualCompletion: "11 Apr 2025",
    createdBy: "Divya Shetty",
    createdDate: "30 Mar 2025 08:55 AM",
    lastUpdated: "11 Apr 2025 07:20 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 250, completedQty: 250, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 250, completedQty: 250, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 250, completedQty: 250, status: "Completed" },
      { step: 4, workCenter: "Packing Section", plannedQty: 250, completedQty: 250, status: "Completed" },
    ],
  },
  {
    id: "18",
    orderNo: "PO-1239",
    product: "Side Table",
    unit: "Unit 3",
    outlet: "Marathahalli",
    plannedQty: 80,
    completedQty: 30,
    status: "In Progress",
    plannedDate: "27 May 2025",
    startDate: "17 May 2025",
    expectedCompletion: "03 Jun 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "15 May 2025 03:10 PM",
    lastUpdated: "17 May 2025 02:40 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 80, completedQty: 60, status: "In Progress" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 80, completedQty: 30, status: "In Progress" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 80, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 80, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "19",
    orderNo: "PO-1238",
    product: "Bookshelf",
    unit: "Unit 1",
    outlet: "Jayanagar",
    plannedQty: 55,
    completedQty: 55,
    status: "Completed",
    plannedDate: "08 Apr 2025",
    startDate: "29 Mar 2025",
    expectedCompletion: "08 Apr 2025",
    actualCompletion: "07 Apr 2025",
    createdBy: "Admin",
    createdDate: "27 Mar 2025 10:15 AM",
    lastUpdated: "07 Apr 2025 04:50 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 55, completedQty: 55, status: "Completed" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 55, completedQty: 55, status: "Completed" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 55, completedQty: 55, status: "Completed" },
      { step: 4, workCenter: "Packing Section", plannedQty: 55, completedQty: 55, status: "Completed" },
    ],
  },
  {
    id: "20",
    orderNo: "PO-1237",
    product: "Dining Table 6 Seater",
    unit: "Unit 2",
    outlet: "Whitefield",
    plannedQty: 40,
    completedQty: 15,
    status: "In Progress",
    plannedDate: "29 May 2025",
    startDate: "19 May 2025",
    expectedCompletion: "05 Jun 2025",
    actualCompletion: null,
    createdBy: "Ravi Kumar",
    createdDate: "17 May 2025 09:00 AM",
    lastUpdated: "17 May 2025 09:00 AM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 40, completedQty: 30, status: "In Progress" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 40, completedQty: 15, status: "In Progress" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 40, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 40, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "21",
    orderNo: "PO-1236",
    product: "3 Seater Sofa",
    unit: "Unit 3",
    outlet: "HSR Layout",
    plannedQty: 75,
    completedQty: 75,
    status: "Completed",
    plannedDate: "03 Apr 2025",
    startDate: "24 Mar 2025",
    expectedCompletion: "03 Apr 2025",
    actualCompletion: "02 Apr 2025",
    createdBy: "Admin",
    createdDate: "22 Mar 2025 11:30 AM",
    lastUpdated: "02 Apr 2025 05:15 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 75, completedQty: 75, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 75, completedQty: 75, status: "Completed" },
      { step: 3, workCenter: "Foam Section", plannedQty: 75, completedQty: 75, status: "Completed" },
      { step: 4, workCenter: "Stitching Section", plannedQty: 75, completedQty: 75, status: "Completed" },
      { step: 5, workCenter: "Finishing Section", plannedQty: 75, completedQty: 75, status: "Completed" },
      { step: 6, workCenter: "Packing Section", plannedQty: 75, completedQty: 75, status: "Completed" },
    ],
  },
  {
    id: "22",
    orderNo: "PO-1235",
    product: "Office Chair",
    unit: "Unit 1",
    outlet: "Koramangala",
    plannedQty: 95,
    completedQty: 40,
    status: "In Progress",
    plannedDate: "30 May 2025",
    startDate: "20 May 2025",
    expectedCompletion: "06 Jun 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "18 May 2025 01:00 PM",
    lastUpdated: "17 May 2025 03:30 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 95, completedQty: 80, status: "In Progress" },
      { step: 2, workCenter: "Welding Section", plannedQty: 95, completedQty: 40, status: "In Progress" },
      { step: 3, workCenter: "Upholstery Section", plannedQty: 95, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 95, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "23",
    orderNo: "PO-1234",
    product: "King Size Bed",
    unit: "Unit 2",
    outlet: "Marathahalli",
    plannedQty: 50,
    completedQty: 22,
    status: "In Progress",
    plannedDate: "28 Mar 2025",
    startDate: "18 Mar 2025",
    expectedCompletion: "04 Apr 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "16 Mar 2025 09:45 AM",
    lastUpdated: "17 May 2025 02:00 PM",
    notes: "—",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 50, completedQty: 50, status: "Completed" },
      { step: 2, workCenter: "Welding Section", plannedQty: 50, completedQty: 40, status: "In Progress" },
      { step: 3, workCenter: "Foam Section", plannedQty: 50, completedQty: 22, status: "In Progress" },
      { step: 4, workCenter: "Finishing Section", plannedQty: 50, completedQty: 0, status: "Pending" },
      { step: 5, workCenter: "Packing Section", plannedQty: 50, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "24",
    orderNo: "PO-1233",
    product: "Wardrobe 3 Door",
    unit: "Unit 1",
    outlet: "Jayanagar",
    plannedQty: 28,
    completedQty: 0,
    status: "Pending",
    plannedDate: "02 Jun 2025",
    startDate: "—",
    expectedCompletion: "10 Jun 2025",
    actualCompletion: null,
    createdBy: "Admin",
    createdDate: "17 May 2025 04:20 PM",
    lastUpdated: "17 May 2025 04:20 PM",
    notes: "Awaiting hardware fittings stock.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 28, completedQty: 0, status: "Pending" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 28, completedQty: 0, status: "Pending" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 28, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 28, completedQty: 0, status: "Pending" },
    ],
  },
  {
    id: "25",
    orderNo: "PO-1232",
    product: "Dining Chair",
    unit: "Unit 3",
    outlet: "Whitefield",
    plannedQty: 180,
    completedQty: 0,
    status: "On Hold",
    plannedDate: "04 Jun 2025",
    startDate: "21 May 2025",
    expectedCompletion: "12 Jun 2025",
    actualCompletion: null,
    createdBy: "Manoj Pillai",
    createdDate: "19 May 2025 10:50 AM",
    lastUpdated: "17 May 2025 01:25 PM",
    notes: "On hold — fabric supplier delay.",
    steps: [
      { step: 1, workCenter: "Cutting Section", plannedQty: 180, completedQty: 50, status: "On Hold" },
      { step: 2, workCenter: "Assembly Section", plannedQty: 180, completedQty: 0, status: "Pending" },
      { step: 3, workCenter: "Finishing Section", plannedQty: 180, completedQty: 0, status: "Pending" },
      { step: 4, workCenter: "Packing Section", plannedQty: 180, completedQty: 0, status: "Pending" },
    ],
  },
];

export const PRODUCTS = ["All Products", "3 Seater Sofa", "King Size Bed", "Dining Chair", "Wardrobe 3 Door", "Center Table", "TV Unit", "Office Chair", "Dining Table 6 Seater", "Side Table", "Bookshelf"];
export const UNITS = ["All Units", "Unit 1", "Unit 2", "Unit 3"];
export const STATUSES = ["All Status", "In Progress", "Completed", "Pending", "On Hold", "Cancelled"];